name: Deploy Backend

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: aayushxjoshi/monorepo-backend:${{github.sha}}

      - name: Docker to SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@100.52.152.26 << 'EOF'

          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          sudo docker pull aayushxjoshi/monorepo-backend:${{ github.sha }}

          sudo docker stop monorepo:backend || true

          sudo docker rm monorepo-backend || true

          # Run new container
          sudo docker run -d \
            --name monorepo-backend \
            -p 8000:8000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            aayushxjoshi/monorepo-backend:${{ github.sha }}

          EOF
